services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=user_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"